apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post-service
  type: NodePort
  ports:
    - port: 80               # External port
      targetPort: 5001       # Container port
      nodePort: 30501        # NodePort exposed on the host
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: tdhoa97/post-service:v1
          ports:
            - containerPort: 5001
          env:
            - name: DB_HOST
              value: postgres
