apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post-service
  ports:
    - port: 80
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  selector:
    matchLabels:
      app: post-service
  replicas: 1
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: tdhoa97/post-service:v1
          ports:
            - containerPort: 5001
              targetPort: 5001
              nodePort: 30501
          env:
            - name: DB_HOST
              value: postgres
