# monitoring/prometheus-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'user-service-nodeport'
        static_configs:
          - targets: ['192.168.0.140:30500']

      - job_name: 'post-service-nodeport'
        static_configs:
          - targets: ['192.168.0.140:30501']
