apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'post-service'
        static_configs:
          - targets: ['post-service:5001']
      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:5000']
